-- MySQL Script generated by MySQL Workbench
-- 03/25/16 23:58:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gopungut
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gopungut` ;

-- -----------------------------------------------------
-- Schema gopungut
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gopungut` DEFAULT CHARACTER SET utf8 ;
USE `gopungut` ;

-- -----------------------------------------------------
-- Table `gopungut`.`Penjual_Sampah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gopungut`.`Penjual_Sampah` (
  `id_penjual` INT NOT NULL AUTO_INCREMENT,
  `nama_penjual` VARCHAR(45) NULL,
  `alamat_penjual` VARCHAR(45) NULL,
  `password_penjual` VARCHAR(45) NULL,
  `username_penjual` VARCHAR(45) NULL,
  `noHp_penjual` VARCHAR(12) NULL,
  PRIMARY KEY (`id_penjual`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gopungut`.`sampah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gopungut`.`sampah` (
  `id_kategori` INT NOT NULL AUTO_INCREMENT,
  `kategori` VARCHAR(45) NULL,
  PRIMARY KEY (`id_kategori`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gopungut`.`menjual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gopungut`.`menjual` (
  `Penjual_Sampah_id_penjual` INT NOT NULL,
  `sampah_id_kategori` INT NOT NULL,
  `tgl_upload` TIMESTAMP NOT NULL,
  `kuantitas` INT NULL,
  `uang_diterima` INT NULL,
  `hasSold` TINYINT(1) NULL,
  PRIMARY KEY (`Penjual_Sampah_id_penjual`, `sampah_id_kategori`, `tgl_upload`),
  INDEX `fk_Penjual_Sampah_has_sampah_sampah1_idx` (`sampah_id_kategori` ASC),
  INDEX `fk_Penjual_Sampah_has_sampah_Penjual_Sampah_idx` (`Penjual_Sampah_id_penjual` ASC),
  CONSTRAINT `fk_Penjual_Sampah_has_sampah_Penjual_Sampah`
    FOREIGN KEY (`Penjual_Sampah_id_penjual`)
    REFERENCES `gopungut`.`Penjual_Sampah` (`id_penjual`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Penjual_Sampah_has_sampah_sampah1`
    FOREIGN KEY (`sampah_id_kategori`)
    REFERENCES `gopungut`.`sampah` (`id_kategori`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gopungut`.`pengelola_sampah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gopungut`.`pengelola_sampah` (
  `id_pengelola_sampah` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password_pengelola` VARCHAR(45) NULL,
  `email_pengelola` VARCHAR(45) NULL,
  `noHp_pengelola` VARCHAR(12) NULL,
  PRIMARY KEY (`id_pengelola_sampah`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gopungut`.`kurir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gopungut`.`kurir` (
  `id_kurir` INT NOT NULL AUTO_INCREMENT,
  `nama_kurir` VARCHAR(45) NULL,
  `username_kurir` VARCHAR(45) NULL,
  `password_kurir` VARCHAR(45) NULL,
  `noHp_kurir` VARCHAR(12) NULL,
  PRIMARY KEY (`id_kurir`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gopungut`.`membeli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gopungut`.`membeli` (
  `sampah_id_kategori` INT NOT NULL,
  `pengelola_sampah_id_pengelola_sampah` INT NOT NULL,
  `tanggal_request` TIMESTAMP NOT NULL,
  `minimumQuantity` INT NULL,
  `harga_tetapan` INT NULL,
  `kurir_id_kurir` INT NOT NULL,
  `butuhKurir` TINYINT(1) NULL,
  `subtotal_pembelian` INT NULL,
  `biaya_kurir` INT NULL,
  PRIMARY KEY (`sampah_id_kategori`, `pengelola_sampah_id_pengelola_sampah`, `tanggal_request`),
  INDEX `fk_sampah_has_pengelola_sampah_pengelola_sampah1_idx` (`pengelola_sampah_id_pengelola_sampah` ASC),
  INDEX `fk_sampah_has_pengelola_sampah_sampah1_idx` (`sampah_id_kategori` ASC),
  INDEX `fk_membeli_kurir1_idx` (`kurir_id_kurir` ASC),
  CONSTRAINT `fk_sampah_has_pengelola_sampah_sampah1`
    FOREIGN KEY (`sampah_id_kategori`)
    REFERENCES `gopungut`.`sampah` (`id_kategori`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sampah_has_pengelola_sampah_pengelola_sampah1`
    FOREIGN KEY (`pengelola_sampah_id_pengelola_sampah`)
    REFERENCES `gopungut`.`pengelola_sampah` (`id_pengelola_sampah`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_membeli_kurir1`
    FOREIGN KEY (`kurir_id_kurir`)
    REFERENCES `gopungut`.`kurir` (`id_kurir`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `gopungut` ;

-- -----------------------------------------------------
-- Placeholder table for view `gopungut`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gopungut`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `gopungut`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gopungut`.`view1`;
USE `gopungut`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
